version: '3.9'
services:
  postgres:
    image: postgres
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - my-network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - my-network
    restart: unless-stopped

  config-server-ms:
    image: juliettegodyere/config-server-ms:latest
    container_name: config-server-ms
    ports:
      - 8080:8080
    depends_on:
      - servicereg
    networks:
      - microservice-network
      - my-network
    environment:
      - eureka.client.serviceURL.defaultZone=http://servicereg:8761/eureka/
      - SPRING_PROFILES_ACTIVE=docker

  servicereg:
    image: juliettegodyere/servicereg:latest
    container_name: servicereg
    ports:
      - 8761:8761
    depends_on:
      - rabbitmq
      - zipkin
      - postgres
      - pgadmin
    networks:
      - microservice-network
      - my-network

  companyms:
    image: juliettegodyere/companyms:latest
    container_name: company
    ports:
      - 8081:8081
    depends_on:
      - servicereg
#      - config-server-ms
    networks:
      - microservice-network
      - my-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  jobms:
    image: juliettegodyere/jobms:latest
    container_name: job
    ports:
      - 8082:8082
    depends_on:
      - servicereg
#      - config-server-ms
    networks:
      - microservice-network
      - my-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://servicereg:8761/eureka

#  jobms1:
#    image: juliettegodyere/jobms:latest
#    container_name: job1
#    ports:
#      - 8082:8082
#    depends_on:
#      - servicereg
#      - config-server-ms
#    networks:
#      - microservice-network
#      - my-network
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://servicereg:8761/eureka

  reviewms:
    image: juliettegodyere/reviewms:latest
    container_name: review
    ports:
      - 8083:8083
    depends_on:
      - servicereg
#      - config-server-ms
    networks:
      - microservice-network
      - my-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - microservice-network
      - my-network

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411
    networks:
      - microservice-network
      - my-network

  gateway-ms:
    image: juliettegodyere/gateway-ms:latest
    ports:
      - 8084:8084
    depends_on:
      - servicereg
    networks:
      - microservice-network
      - my-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

volumes:
  postgres:
  pgadmin:

networks:
  microservice-network:
    driver: bridge
  my-network:
    driver: bridge